### ISSUE TITLE
Saving Dialog Progress Bar

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataProcessor2#25]
When the Saving is done the Progress Bar disappears.
This is confusing, because one cannot see anymore that it finished.
I think it would say FINISHED or something....

**Comment by ASHISRAVINDRAN** [comment]
Now save window will show "Saving Completed" when Progress Bar disappears and will show "Saving Interrupted" when `Stop Saving` button is clicked.
