### ISSUE TITLE
Bounding Box

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataProcessor2#26]
Look at this:
https://forum.image.sc/t/real-box-selection-dialogs-in-bigdataviewer/22650
We should use that.

:-)

**Comment by tischi** [comment]
@ASHISRAVINDRAN 
If you look for something to do :-)
We should implement this new SelectionBox in BDC:
https://github.com/bigdataviewer/bigdataviewer-vistools/blob/3385dd49c3a96946e16d34684dce9d15a5b45740/src/test/java/bdv/util/RealBoxSelectionExample.java

**Comment by ASHISRAVINDRAN** [comment]
Hi Tischi,
We now have the new bounding box for cropping and tracking ROI selection! :) 
Still, some of old bounding box code is kept as its used as an overlay for tracked regions.
Note that pom.xml is also updated for availing the latest changes from BigDataViewer jars (core& vis-tools)

**Comment by tischi** [comment]
Awesome! I will try it out soon!

**Comment by ASHISRAVINDRAN** [comment]
Cropping works fine. Closing issue.
