### ISSUE TITLE
Put ImarisWriter in own repo

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataProcessor2#30]
@ASHISRAVINDRAN 
I am trying to move the ImarisWriter into an own repo:
https://github.com/tischi/imaris-writer
Would be good if this repo then would just depend on it.
I am in the process...I'll let you know once it is done and then you could refactor the BDT2 code.

**Comment by tischi** [comment]
I just pushed a version that compiles.
Could you please try to depend on it?

**Comment by ASHISRAVINDRAN** [comment]
Hi Tischi,
Done!
Now this repo depends on imaris-writer repo. 
I have a suggestion for imaris-writer jar group id. This is currently `de.embl.cba` which is pretty generic. Do you think its better to be specific `de.embl.cba.imaris` to avoid some dependency misidentification error in the future?

**Comment by tischi** [comment]
…I thought group id should be generic?

For example:

<dependency>
    <groupId>net.imagej</groupId>
    <artifactId>imagej-legacy</artifactId>
</dependency>

<dependency>
    <groupId>net.imagej</groupId>
    <artifactId>imagej</artifactId>
</dependency>

<dependency>
    <groupId>net.imagej</groupId>
    <artifactId>imagej-common</artifactId>
</dependency>

**Comment by ASHISRAVINDRAN** [comment]
Yes, you are right. 
I suggested because I remember you had some issue with similar package names in different jars. Never mind!
