### ISSUE TITLE
Pixel Value Overlay

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataProcessor2#34]
Could you please make the Font maybe 2x larger?

<img width="175" alt="image" src="https://user-images.githubusercontent.com/2157566/54087766-c998e600-4356-11e9-9147-9ac372c69497.png">

**Comment by ASHISRAVINDRAN** [comment]
I had handcrafted the value font size and position for the best organic alignment with the coordinate values. For me, it looks like this (most of the times):
![gray](https://user-images.githubusercontent.com/33703127/54114414-addf1f80-43ea-11e9-8d55-34a0337c45be.png)

Seems like this alignment could change depending on the machine. :( 
I will push the changes with a bigger font size now.

**Comment by ASHISRAVINDRAN** [comment]
Font size is now changed from 12 to 20 and it currently looks like this (in my machine):
![new_gray](https://user-images.githubusercontent.com/33703127/54114819-889ee100-43eb-11e9-8e3e-615cd7a3de55.png)
You may play with the font size (and consequently the value text position) here:
https://github.com/tischi/fiji-plugin-bigDataProcessor2/blob/447c398e1e6ba9555225dfe264bc7a8be5d0784b/src/main/java/de/embl/cba/bdp2/viewers/BdvImageViewer.java#L284

and 

https://github.com/tischi/fiji-plugin-bigDataProcessor2/blob/447c398e1e6ba9555225dfe264bc7a8be5d0784b/src/main/java/de/embl/cba/bdp2/viewers/BdvGrayValuesOverlay.java#L38

**Comment by tischi** [comment]
Thanks!
