### ISSUE TITLE
messing up

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataProcessor2#38]
@ASHISRAVINDRAN 
Could you please check whether you can still pull and work with it?
I kind of messed up by working on branches and not managing to properly merge them into master. So I forced it....hope I did not mess it up too much.

**Comment by ASHISRAVINDRAN** [comment]
Prima facie, I can see that my last commit made on Sunday, the 151th commit, is lost.
It was done to enable multiple saving processes in parallel.
The current state of repo build doesn't seem to have build errors. (I can't run and test now, will have to wait until tonight to really run the code). So if you see your commits are merged fine then we should be good. :)
Either you can try to undo the merge or if its too much trouble I can push my changes again! Lemme know!
I would take approx 1-2h to put the code back and test.

**Comment by tischi** [comment]
But you locally still have your code!
Can't you just merge your code into the new one?

You can go back to a recent commit where you still have your code, checkout a branch from there, then pull the new master and merge the branch into the master.
I think :)
This will be a good git exercise for you :-)

**Comment by tischi** [comment]
Alternative is that I do the merging.
You have to:

1. find the commit on your computer where you added the changes
2. checkout a new branch from this commit
     `- git checkout -b ashisBranch`
3. push this branch to github
     `- git push --set-upstream origin ashisBranch`
4. I will then try to figure out how to merge it back into master

**Comment by ASHISRAVINDRAN** [comment]
Thanks for breaking it down for me! 
So we have the new branch ```fix_merge_branch``` which has my commit as its latest change.

**Comment by ASHISRAVINDRAN** [comment]
Github suggested to a make a PR from ```fix_merge_branch``` to ```master```. This PR only contains my changes. Since only this commit (Commit SHA: 04a48534a8e7cd04a1550134b6ee54b990bbb7c4) is missing, I suppose merging this PR will fix the issue.

**Comment by ASHISRAVINDRAN** [comment]
Since the PR and branch have been merged, I am closing the issue and deleting the redundant branch.
