### ISSUE TITLE
Error when using the "Bin" function

### ISSUE THREAD

**Issue by metavibor** [tischi/fiji-plugin-bigDataProcessor2#54]
When I attempt to use the "bin" function AFTER I have used the ChromaticShiftCorrection function, when clicking on one of the arrows to indicate the amount of binning, an error "Could not wrap as volatile!" appears. 
This does not happen when doing first the binning and than the chromatic correction. 
The reason why one would like to do the chromatic correction before the binning is that one can correct with better precision before the 3x3 binning for example.
Is this connected with the fact you recently changed the Bdv behavior during ChromaticShiftCorrection function but not during "Bin"?

**Comment by tischi** [comment]
This has some deep internal reasons. I will dig into the code :-)
After all, it is in fact not so simple to chain all these "views" on TB sized data (but cool ;-).

**Comment by tischi** [comment]
@metavibor 
It should work now. 
Could you please update, test and confirm?
