### ISSUE TITLE
Cannot open Luxendo InVi-SPIM files

### ISSUE THREAD

**Issue by metavibor** [tischi/fiji-plugin-bigDataProcessor2#65]
Hi Tischi,
Luxendo minimally changed the file structure of the data coming from the InVi-SPIM and now the data cannot be opened with "presets"offered by bigDataProcessor2 (the same is with bigDataProcessor). They have some additional files in the structure such as: 
Cam_Long.json (there was a .txt file in the previous file structure version)
and
Cam_Long_All.h5 (completely new file, not sure what is in it, it is tiny, no imaging data)
I'm not sure if this is the reason why I cannot open new InVi files... If I delete these files I still have a problem... 
bigDataProcessor2 does not work at all no matter what I do but I can get bigDataProcessor to work if I delete the "Cam_Long_All.h5" file and manually change the "Only load files matching" preset  from ".*long.*" to  ".*Long.*" (just made the "L" capital)
Opening old files still works fine.

**Comment by tischi** [comment]
If you update your Fiji, there should be this option now:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/2157566/67759016-00834f80-fa3f-11e9-8e12-393130557fde.png">
This worked for our data here. Does it work for you?

**Comment by metavibor** [comment]
works for me as well. Thanks!
